import type { DashboardData,EventView,IncidentView,MetricValue,ModelView } from '../types/dashboard'
import { api } from './endpoints'
import type { ApiAuditEvent,ApiDiagnosis,ApiHealthTimeline,ApiIncident,ApiRecovery } from './types'

const metricLabels:Record<string,string>={quality:'Quality',groundedness:'Groundedness',semantic_stability:'Semantic stability',temporal_stability:'Temporal stability',safety:'Safety',drift:'Drift resistance',reliability:'Reliability',latency:'Latency score',cost:'Cost efficiency'}
const eventLabels:Record<string,string>={'demo.reset':'Demo scenario reset','diagnosis.created':'Root cause diagnosed','recovery.approved':'Recovery approved','recovery.execution_started':'Recovery applied','recovery.verified':'Verification passed','incident.created':'Incident created','incident.resolved':'Incident resolved','telemetry.recorded':'Evaluation recorded'}

function metricsFromHealth(health:ApiHealthTimeline):MetricValue[]{const snapshots=health.snapshots;const latest=snapshots.at(-1);const previous=snapshots.at(-2);if(!latest)return[];return Object.entries(latest.dimensions).filter(([,v])=>v!==null&&v!==undefined).map(([key,value])=>({key,label:metricLabels[key]??key,value:value??null,previous:previous?.dimensions[key as keyof typeof previous.dimensions]??null}))}
function modelFromHealth(health:ApiHealthTimeline,activeIncidents:number):ModelView{const latest=health.snapshots.at(-1);return{id:health.model.id,name:health.model.name,provider:health.model.provider,environment:health.model.environment,lifecycle:health.model.status,description:health.model.description,status:latest?.state??'insufficient_data',score:latest?.score??null,metrics:metricsFromHealth(health),trend:health.snapshots.map(s=>({time:s.observed_at,score:s.score,groundedness:s.dimensions.groundedness,quality:s.dimensions.quality,safety:s.dimensions.safety,stability:s.dimensions.semantic_stability,drift:s.dimensions.drift})),lastEvaluation:latest?.observed_at??null,sampleSize:latest?.sample_size,coverage:latest?.coverage,activeIncidents,forecast:health.forecast?{score:health.forecast.predicted_score,direction:health.forecast.direction,horizonMinutes:health.forecast.horizon_minutes}:null}}
function eventStatus(type:string):EventView['status']{if(type.includes('failed')||type.includes('critical'))return'critical';if(type.includes('incident')||type.includes('diagnos'))return'warning';if(type.includes('verified')||type.includes('resolved')||type.includes('passed'))return'success';return'info'}
function incidentFromApi(i:ApiIncident,modelName:string,provider:string,diagnosis:ApiDiagnosis|null,recovery:ApiRecovery|null):IncidentView{const d=diagnosis?.incident_id===i.id?diagnosis:null;const r=recovery?.incident_id===i.id?recovery:null;return{id:i.id,modelId:i.model_id,modelName,provider,title:i.title,state:i.state,severity:i.severity,openedAt:i.opened_at,closedAt:i.closed_at,baselineScore:i.baseline_score,troughScore:i.trough_score,summary:i.summary,probableCause:d?.probable_cause.replaceAll('_',' '),confidence:d?.confidence,evidence:d?.evidence.map(e=>({metric:e.metric,summary:e.summary,baseline:e.baseline_value,current:e.current_value}))??[],recovery:r?{id:r.id,state:r.state,risk:r.risk,requiresApproval:r.requires_approval,actions:r.actions,verification:r.verification?{baselineScore:r.verification.baseline_score,postScore:r.verification.post_score,passed:r.verification.passed,observedRequests:r.verification.observed_requests,requiredRequests:r.verification.required_requests}:null}:null}}
function eventFromAudit(e:ApiAuditEvent,modelName:string):EventView{return{id:e.id,modelId:e.model_id,modelName,type:e.event_type,title:eventLabels[e.event_type]??e.event_type.replaceAll(/[._]/g,' '),detail:e.reason??(typeof e.details.summary==='string'?e.details.summary:null),timestamp:e.created_at,status:eventStatus(e.event_type)}}

export async function loadLiveDashboard():Promise<DashboardData>{await api.healthcheck();const models=await api.models();const bundles=await Promise.all(models.map(async model=>{const[health,incidents,audit]=await Promise.all([api.health(model.id),api.incidents(model.id),api.audit(model.id)]);const open=incidents.filter(i=>i.state!=='resolved');let diagnosis:ApiDiagnosis|null=null;let recovery:ApiRecovery|null=null;if(incidents.length)[diagnosis,recovery]=await Promise.all([api.diagnosis(model.id).catch(()=>null),api.recovery(model.id).catch(()=>null)]);return{model:modelFromHealth(health,open.length),incidents:incidents.map(i=>incidentFromApi(i,model.name,model.provider,diagnosis,recovery)),events:audit.map(e=>eventFromAudit(e,model.name))}}));return{models:bundles.map(b=>b.model),incidents:bundles.flatMap(b=>b.incidents).sort((a,b)=>Date.parse(b.openedAt)-Date.parse(a.openedAt)),events:bundles.flatMap(b=>b.events).sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp)),evaluationsToday:bundles.reduce((sum,b)=>sum+(b.model.sampleSize??0),0)}}
