export interface ApiModel { id:string;name:string;provider:string;environment:string;description:string|null;status:'active'|'paused'|'retired';retention_days:number;created_at:string;updated_at:string }
export interface ApiGroqCatalog { models:string[] }
export interface ApiGroqEvaluationProfile { expected_terms:string[];trusted_facts:string[];forbidden_terms:string[];expected_json:boolean;latency_target_ms:number;cost_target_usd?:number;input_cost_per_million:number;output_cost_per_million:number }
export interface ApiGroqEvaluation { model_id:string;model_identifier:string;responses:Array<{text:string;latency_ms:number;input_tokens:number;output_tokens:number}>;dimensions:ApiDimensions;health_score:number|null;confidence:number;evidence:{expected_terms?:Record<string,boolean>;trusted_facts?:Record<string,boolean>;forbidden_terms_found?:string[];average_latency_ms?:number;estimated_cost_usd?:number;responses_compared?:number};formula:string;snapshot:ApiSnapshot }
export interface ApiDimensions { quality?:number|null;groundedness?:number|null;semantic_stability?:number|null;temporal_stability?:number|null;safety?:number|null;drift?:number|null;reliability?:number|null;latency?:number|null;cost?:number|null }
export interface ApiSnapshot { id:string;model_id:string;observed_at:string;dimensions:ApiDimensions;score:number|null;state:'healthy'|'warning'|'critical'|'insufficient_data';confidence:number;sample_size:number;coverage:number;source:string;missing_dimensions:string[] }
export interface ApiHealthTimeline { model:ApiModel;snapshots:ApiSnapshot[];forecast:{horizon_minutes:number;predicted_score:number;lower_bound:number;upper_bound:number;change_per_hour:number;direction:string;method:string}|null }
export interface ApiIncident { id:string;model_id:string;title:string;state:string;severity:string;opened_at:string;closed_at:string|null;baseline_score:number|null;trough_score:number|null;summary:string|null }
export interface ApiDiagnosis { id:string;model_id:string;incident_id:string|null;probable_cause:string;confidence:number;status:string;created_at:string;evidence:Array<{reason_code:string;metric:string;summary:string;baseline_value:number|null;current_value:number|null}> }
export interface ApiRecovery { id:string;model_id:string;incident_id:string|null;state:string;risk:string;version:number;approval_level:string;requires_approval:boolean;failure_reason:string|null;actions:Array<{code:string;title:string;description:string;risk:string;reversible:boolean}>;verification:{baseline_score:number|null;post_score:number|null;passed:boolean|null;observed_requests:number;required_requests:number}|null }
export interface ApiRecoveryCommand { id:string;plan_id:string;command_type:string;state:'pending'|'running'|'succeeded'|'failed'|'canceled';idempotency_key:string;actor:string;actor_role:string;attempt:number;max_attempts:number;requested_at:string;completed_at:string|null;error:string|null }
export interface ApiAuditEvent { id:string;model_id:string|null;event_type:string;actor:string;reason:string|null;details:Record<string,unknown>;created_at:string }
export interface ApiAlert { id:string;model_id:string;incident_id:string|null;state:string;severity:string;message:string;observed_value:number|null;fired_at:string;resolved_at:string|null }
export interface ApiAlertFeed { items:ApiAlert[];total:number;firing:number;acknowledged:number }
export type ApiAlertRuleType='threshold'|'transition'|'trajectory'|'coverage'|'evaluation_freshness'
export type ApiAlertMetric='score'|'quality'|'groundedness'|'semantic_stability'|'temporal_stability'|'safety'|'drift'|'reliability'|'latency'|'cost'|'state'|'coverage'|'forecast_score'|'forecast_change_per_hour'|'evaluation_age_minutes'
export type ApiComparator='lt'|'lte'|'gt'|'gte'
export type ApiSeverity='info'|'low'|'medium'|'high'|'critical'
export interface ApiAlertRuleInput { name:string;rule_type:ApiAlertRuleType;metric:ApiAlertMetric;comparator:ApiComparator|null;threshold:number|null;target_state:'healthy'|'warning'|'critical'|null;window_minutes:number;cooldown_minutes:number;minimum_consecutive_windows:number;severity:ApiSeverity;channel:'in_app';is_enabled:boolean }
export interface ApiAlertRule extends ApiAlertRuleInput { id:string;model_id:string;created_at:string;updated_at:string }
export interface ApiEvidenceChunk { id:string;source_id:string;ordinal:number;text:string;evidence_quote:string;locator:Record<string,unknown>;content_hash:string;validation_status:'deterministic'|'exact_match';created_at:string }
export interface ApiEvidenceSource { id:string;model_id:string;name:string;filename:string;media_type:string;content_hash:string;corpus_version:string;status:'awaiting_review'|'approved'|'rejected'|'retired';extraction_method:string;llm_provider:string|null;llm_model:string|null;chunk_count:number;approved_by:string|null;approved_at:string|null;rejection_reason:string|null;created_at:string;updated_at:string;chunks:ApiEvidenceChunk[] }
export interface ApiEvidenceHit { chunk_id:string;source_id:string;source_name:string;filename:string;corpus_version:string;text:string;evidence_quote:string;locator:Record<string,unknown>;relevance:number }
export interface ApiModelConnection { id:string;model_id:string;kind:'github'|'telemetry'|'api'|'website';name:string;api_endpoint:string|null;credential_configured:boolean;status:'configured'|'connected'|'error'|'needs_setup'|'paused';last_error:string|null }
export interface ApiAutomatedEvaluationCase { question:string;expected:string;actual:string;passed:boolean;failure_reason:string|null;field:string;source_id:string;source_name:string;locator:Record<string,unknown>;latency_ms:number }
export interface ApiAutomatedEvaluation { model_id:string;connection:string;generated_questions:number;passed_questions:number;failed_questions:number;pass_rate:number;dimensions:ApiDimensions;health_score:number|null;health_state:ApiSnapshot['state'];confidence:number;message:string;formula:string;cases:ApiAutomatedEvaluationCase[];snapshot:ApiSnapshot }
