import type { DashboardData,DemoStage,EventView,HealthPoint,IncidentView,MetricValue,ModelView } from '../types/dashboard'

const now=Date.now();const at=(minutes:number)=>new Date(now+minutes*60_000).toISOString()
const point=(minutes:number,score:number,groundedness:number,quality:number,safety=98,stability=92,drift=95):HealthPoint=>({time:at(minutes),score,groundedness,quality,safety,stability,drift})
const healthyTrend=[point(-180,92,94,91),point(-150,94,95,93),point(-120,93,96,94),point(-90,95,96,95),point(-60,94,95,94),point(-30,96,97,95),point(0,95,96,95)]
const failedTrend=[...healthyTrend.slice(0,3),point(-50,86,79,88,97,84,78),point(-35,74,61,78,96,70,58),point(-20,62,38,69,96,57,34),point(0,58,34,65,95,53,29)]
const recoveryTrend=[...failedTrend,point(5,66,49,72,96,61,44),point(10,77,68,81,97,75,65)]
const verifiedTrend=[...failedTrend.slice(-4),point(-10,72,61,78,96,70,59),point(-5,86,84,89,98,85,82),point(0,93,94,93,99,91,92)]

function values(stage:DemoStage):MetricValue[]{const current={healthy:[96,95,99,92,95],degraded:[34,65,95,53,29],recovering:[68,81,97,75,65],verified:[94,93,99,91,92]}[stage];const previous=stage==='healthy'?[95,94,98,91,94]:[96,95,99,92,95];return['Groundedness','Quality','Safety','Semantic stability','Drift resistance'].map((label,i)=>({key:label.toLowerCase().replaceAll(' ','_'),label,value:current[i],previous:previous[i]}))}
const baseEvents:EventView[]=[
  {id:'evt-1',modelId:'campus-gpt',modelName:'CampusGPT',type:'evaluation.passed',title:'Evaluation passed',detail:'Health score 95 · 48 samples',timestamp:at(0),status:'success'},
  {id:'evt-2',modelId:'campus-gpt',modelName:'CampusGPT',type:'groundedness.passed',title:'Groundedness check passed',detail:'96 / 100',timestamp:at(-1),status:'success'},
  {id:'evt-3',modelId:'loan-risk',modelName:'LoanRiskModel',type:'forecast.stable',title:'Forecast remains stable',detail:'Next 30 minutes',timestamp:at(-4),status:'info'},
  {id:'evt-4',modelId:'campus-gpt',modelName:'CampusGPT',type:'evaluation.passed',title:'Evaluation passed',detail:'Health score 94 · 46 samples',timestamp:at(-7),status:'success'},
]
const failureEvents:EventView[]=[
  {id:'evt-f4',modelId:'campus-gpt',modelName:'CampusGPT',type:'incident.created',title:'Incident created',detail:'Knowledge freshness failure · Critical',timestamp:at(0),status:'critical'},
  {id:'evt-f3',modelId:'campus-gpt',modelName:'CampusGPT',type:'evaluation.failed',title:'Evaluation failed',detail:'Health score fell below 60',timestamp:at(-.2),status:'critical'},
  {id:'evt-f2',modelId:'campus-gpt',modelName:'CampusGPT',type:'degradation.detected',title:'Grounding degradation detected',detail:'34 / 100 · down 62 points',timestamp:at(-.4),status:'warning'},
  {id:'evt-f1',modelId:'campus-gpt',modelName:'CampusGPT',type:'forecast.deteriorating',title:'Early warning triggered',detail:'Predicted health 48 in 30 minutes',timestamp:at(-2),status:'warning'},...baseEvents]
function incident(stage:DemoStage):IncidentView{return{id:'inc-campus-001',modelId:'campus-gpt',modelName:'CampusGPT',provider:'Qwen',title:'Knowledge grounding collapse',state:stage==='verified'?'resolved':stage==='recovering'?'verifying':'open',severity:'critical',openedAt:at(-1),closedAt:stage==='verified'?at(0):null,baselineScore:95,troughScore:58,summary:'Answers began relying on stale campus policy data instead of the approved knowledge corpus.',probableCause:'Knowledge freshness failure',confidence:.87,evidence:[{metric:'Groundedness',summary:'Citation support dropped below the reliability threshold.',baseline:96,current:34},{metric:'Drift resistance',summary:'Answer behaviour diverged from the current evaluation baseline.',baseline:95,current:29},{metric:'Semantic stability',summary:'Equivalent questions produced conflicting policy guidance.',baseline:92,current:53}],recovery:{id:'rec-001',state:stage==='verified'?'recovered':stage==='recovering'?'verifying':'recommended',risk:'medium',requiresApproval:true,actions:[{code:'citation_only',title:'Enable citation-only mode',description:'Restrict answers to claims supported by the current approved campus corpus.',risk:'low',reversible:true},{code:'refresh_corpus',title:'Refresh retrieval corpus',description:'Switch retrieval to the verified 2026-09 campus policy index.',risk:'medium',reversible:true}],verification:stage==='verified'?{baselineScore:58,postScore:93,passed:true,observedRequests:24,requiredRequests:20}:stage==='recovering'?{baselineScore:58,postScore:77,passed:null,observedRequests:12,requiredRequests:20}:null}}}
function eventsFor(stage:DemoStage){if(stage==='healthy')return baseEvents;if(stage==='degraded')return failureEvents;if(stage==='recovering')return[{id:'evt-r2',modelId:'campus-gpt',modelName:'CampusGPT',type:'verification.started',title:'Verification in progress',detail:'12 of 20 evaluation requests complete',timestamp:at(0),status:'info' as const},{id:'evt-r1',modelId:'campus-gpt',modelName:'CampusGPT',type:'recovery.applied',title:'Recovery applied',detail:'Citation-only mode · Corpus refreshed',timestamp:at(-1),status:'warning' as const},...failureEvents];return[{id:'evt-v2',modelId:'campus-gpt',modelName:'CampusGPT',type:'incident.resolved',title:'Incident resolved',detail:'CampusGPT returned to healthy state',timestamp:at(0),status:'success' as const},{id:'evt-v1',modelId:'campus-gpt',modelName:'CampusGPT',type:'verification.passed',title:'Recovery verified',detail:'Health 58 → 93 · 24 requests passed',timestamp:at(-.2),status:'success' as const},{id:'evt-r1',modelId:'campus-gpt',modelName:'CampusGPT',type:'recovery.applied',title:'Recovery applied',detail:'Citation-only mode · Corpus refreshed',timestamp:at(-2),status:'warning' as const},...failureEvents]}

export function createDemoData(stage:DemoStage):DashboardData{
  const score={healthy:95,degraded:58,recovering:77,verified:93}[stage];const status:ModelView['status']=stage==='degraded'?'critical':stage==='recovering'?'warning':'healthy';const trend={healthy:healthyTrend,degraded:failedTrend,recovering:recoveryTrend,verified:verifiedTrend}[stage]
  const campus:ModelView={id:'campus-gpt',name:'CampusGPT',provider:'Qwen',environment:'Production',lifecycle:'active',description:'Answers campus policy and student services questions from the approved knowledge base.',status,score,metrics:values(stage),trend,lastEvaluation:at(0),requestId:`eval-cg-${stage}-2481`,sampleSize:48,coverage:.96,activeIncidents:stage==='healthy'||stage==='verified'?0:1,forecast:stage==='degraded'?{score:48,direction:'deteriorating',horizonMinutes:30}:{score:stage==='recovering'?86:94,direction:stage==='recovering'?'recovering':'stable',horizonMinutes:30}}
  const loan:ModelView={id:'loan-risk',name:'LoanRiskModel',provider:'XGBoost',environment:'Staging',lifecycle:'active',description:'Risk scoring model monitored before production promotion.',status:'healthy',score:91,metrics:[{key:'quality',label:'Quality',value:92},{key:'reliability',label:'Reliability',value:94},{key:'drift',label:'Drift resistance',value:88}],trend:[point(-120,89,90,90),point(-90,90,91,91),point(-60,92,93,92),point(-30,91,92,92),point(0,91,92,92)],lastEvaluation:at(-4),requestId:'eval-lr-7732',sampleSize:32,coverage:.88,activeIncidents:0,forecast:{score:90,direction:'stable',horizonMinutes:30}}
  return{models:[campus,loan],incidents:stage==='healthy'?[]:[incident(stage)],events:eventsFor(stage),latestSampleSize:(campus.sampleSize??0)+(loan.sampleSize??0)}
}
