"""DriftZero persistence layer.

Import models, the session dependency and the enums from here::

    from app.db import HealthSnapshot, Trace, get_session

The data model is documented in ``docs/DATA_MODEL.md``.
"""

from __future__ import annotations

from app.db.base import (
    DEFAULT_TENANT_ID,
    DEFAULT_TENANT_SLUG,
    Base,
    IdMixin,
    JSONDict,
    JSONList,
    TenantMixin,
    TimestampMixin,
    UtcDateTime,
    enum_column,
    new_id,
    utc_now,
)
from app.db.enums import (
    ActorType,
    AlertState,
    DiagnosisStatus,
    EvaluatorKind,
    ExecutionState,
    FeedbackVerdict,
    HealthState,
    IncidentState,
    KnowledgeStatus,
    ModelStatus,
    RecoveryState,
    ReviewState,
    RiskLevel,
    Severity,
    SignalSource,
    StabilityKind,
    StabilityVerdict,
    TraceStatus,
)
from app.db.models import (
    Alert,
    AlertRule,
    AuditEvent,
    Diagnosis,
    DiagnosisEvidence,
    EvaluationFeedback,
    EvaluatorVersion,
    HealthForecastRecord,
    HealthPolicy,
    HealthSnapshot,
    Incident,
    KnowledgeDocument,
    KnowledgeSource,
    ModelVersion,
    MonitoredModel,
    RecoveryActionRecord,
    RecoveryExecution,
    RecoveryPlan,
    ReviewQueueItem,
    StabilityClaim,
    StabilityTest,
    StabilityVariant,
    Tenant,
    Trace,
    VerificationRun,
    evidence_traces,
)
from app.db.queries import (
    ensure_default_tenant,
    latest_snapshot,
    purge_expired_traces,
    reset_all_data,
    snapshot_timeline,
)
from app.db.session import (
    Database,
    configure_database,
    get_database,
    get_session,
    reset_database,
)

__all__ = [
    "DEFAULT_TENANT_ID",
    "DEFAULT_TENANT_SLUG",
    "ActorType",
    "Alert",
    "AlertRule",
    "AlertState",
    "AuditEvent",
    "Base",
    "Database",
    "Diagnosis",
    "DiagnosisEvidence",
    "DiagnosisStatus",
    "EvaluationFeedback",
    "EvaluatorKind",
    "EvaluatorVersion",
    "ExecutionState",
    "FeedbackVerdict",
    "HealthForecastRecord",
    "HealthPolicy",
    "HealthSnapshot",
    "HealthState",
    "IdMixin",
    "Incident",
    "IncidentState",
    "JSONDict",
    "JSONList",
    "KnowledgeDocument",
    "KnowledgeSource",
    "KnowledgeStatus",
    "ModelStatus",
    "ModelVersion",
    "MonitoredModel",
    "RecoveryActionRecord",
    "RecoveryExecution",
    "RecoveryPlan",
    "RecoveryState",
    "ReviewQueueItem",
    "ReviewState",
    "RiskLevel",
    "Severity",
    "SignalSource",
    "StabilityClaim",
    "StabilityKind",
    "StabilityTest",
    "StabilityVariant",
    "StabilityVerdict",
    "Tenant",
    "TenantMixin",
    "TimestampMixin",
    "Trace",
    "TraceStatus",
    "UtcDateTime",
    "VerificationRun",
    "configure_database",
    "ensure_default_tenant",
    "enum_column",
    "evidence_traces",
    "get_database",
    "get_session",
    "latest_snapshot",
    "new_id",
    "purge_expired_traces",
    "reset_all_data",
    "reset_database",
    "snapshot_timeline",
    "utc_now",
]
