import { Check,ChevronRight,LoaderCircle,Play,ShieldCheck } from 'lucide-react'
import { useDashboard } from '../../context/DashboardContext'
import type { RecoveryView } from '../../types/dashboard'
import { StatusBadge } from '../common/StatusBadge'

export function RecoveryPanel({recovery}:{recovery:RecoveryView}){const{runRecovery,isDemo,setDemoStage}=useDashboard();const verified=recovery.state==='recovered';const verifying=recovery.state==='verifying';return <section className={`recovery-panel ${verified?'verified':''}`}>
  <div className="section-heading"><div><span className="panel-label">Recommended recovery</span><h3>{verified?'Recovery verified':verifying?'Verification in progress':recovery.actions[0]?.title??'Recovery plan'}</h3></div><StatusBadge status={recovery.state}/></div>
  {verified&&recovery.verification?<div className="verification-result"><div className="verify-icon"><ShieldCheck size={25}/></div><div><strong>Model health restored</strong><p>New evaluations passed the recovery threshold with no safety regression.</p></div><div className="score-change"><span>Health</span><strong>{recovery.verification.baselineScore} <i>→</i> {recovery.verification.postScore}</strong></div></div>:<div className="recovery-actions">{recovery.actions.map((action,i)=><div key={action.code}><span>{i+1}</span><div><strong>{action.title}</strong><p>{action.description}</p></div><small>{action.reversible?'Reversible':'Permanent'}</small></div>)}</div>}
  <div className="recovery-flow"><span className="done"><Check size={11}/>Detected</span><ChevronRight/><span className={verifying||verified?'done':''}>{verifying||verified?<Check size={11}/>:null}Recovery applied</span><ChevronRight/><span className={verifying?'current':verified?'done':''}>{verifying?<LoaderCircle size={11}/>:verified?<Check size={11}/>:null}Verifying</span><ChevronRight/><span className={verified?'done':''}>{verified?<Check size={11}/>:null}Recovered</span></div>
  {!verified&&<div className="recovery-footer">{verifying?<><div><span>Verification requests</span><strong>{recovery.verification?.observedRequests??12} / {recovery.verification?.requiredRequests??20}</strong></div><div className="progress"><i style={{width:`${((recovery.verification?.observedRequests??12)/(recovery.verification?.requiredRequests??20))*100}%`}}/></div>{isDemo&&<button className="button primary" onClick={()=>setDemoStage('verified')}><Check size={15}/>Complete verification</button>}</>:<button className="button primary" onClick={()=>void runRecovery(recovery.id)}><Play size={14}/>Approve & apply recovery</button>}</div>}
  </section>}
