"""Initial DriftZero schema.

Creates the full data model: fleet identity, knowledge corpus, telemetry and
health, incidents and evidence, recovery execution and verification, the
stability evaluations, and governance.

Revision ID: 0001
Revises: (none)
Create Date: 2026-09-06 09:53:48.437176
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_feedback',
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('verdict', sa.Enum('agree', 'disagree', 'unsure', name='feedback_verdict', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_feedback'))
    )
    with op.batch_alter_table('evaluation_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_evaluation_feedback_target', ['target_type', 'target_id'], unique=False)

    op.create_table('evaluator_versions',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('quality', 'groundedness', 'safety', 'semantic_stability', 'temporal_stability', name='evaluator_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model_identifier', sa.String(length=160), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluator_versions')),
    sa.UniqueConstraint('name', 'version', name='name_version')
    )
    with op.batch_alter_table('evaluator_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluator_versions_kind'), ['kind'], unique=False)

    op.create_table('health_policies',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('thresholds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('minimum_sample_size', sa.Integer(), nullable=False),
    sa.Column('minimum_coverage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_policies')),
    sa.UniqueConstraint('version', name=op.f('uq_health_policies_version'))
    )
    op.create_table('tenants',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('monitored_models',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('environment', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'retired', name='model_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('retention_days > 0', name=op.f('ck_monitored_models_retention_positive')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_monitored_models_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitored_models')),
    sa.UniqueConstraint('tenant_id', 'name', name='tenant_name')
    )
    with op.batch_alter_table('monitored_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_models_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_models_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alert_rules',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('comparator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('window_minutes > 0', name=op.f('ck_alert_rules_window_positive')),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_alert_rules_model_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules')),
    sa.UniqueConstraint('model_id', 'name', name='model_name')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_model_id'), ['model_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_type', sa.Enum('human', 'system', 'agent', name='actor_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_audit_events_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_audit_events_model_created', ['model_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('health_snapshots',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('groundedness', sa.Float(), nullable=True),
    sa.Column('semantic_stability', sa.Float(), nullable=True),
    sa.Column('temporal_stability', sa.Float(), nullable=True),
    sa.Column('safety', sa.Float(), nullable=True),
    sa.Column('drift', sa.Float(), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('state', sa.Enum('insufficient_data', 'healthy', 'warning', 'critical', name='health_state', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('trace_count', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.Enum('observed', 'inferred', 'simulated', name='signal_source', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('missing_dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_health_snapshots_confidence_range')),
    sa.CheckConstraint('coverage >= 0 AND coverage <= 1', name=op.f('ck_health_snapshots_coverage_range')),
    sa.CheckConstraint('sample_size >= 0', name=op.f('ck_health_snapshots_sample_size_non_negative')),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name=op.f('ck_health_snapshots_score_range')),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_health_snapshots_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['health_policies.id'], name=op.f('fk_health_snapshots_policy_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_snapshots'))
    )
    with op.batch_alter_table('health_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_snapshots_model_id'), ['model_id'], unique=False)
        batch_op.create_index('ix_health_snapshots_model_observed', ['model_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_snapshots_observed_at'), ['observed_at'], unique=False)

    op.create_table('knowledge_sources',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('corpus_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('fresh', 'stale', 'disabled', name='knowledge_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_knowledge_sources_model_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources'))
    )
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_sources_model_id'), ['model_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('model_identifier', sa.String(length=160), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('tool_set_hash', sa.String(length=64), nullable=False),
    sa.Column('corpus_version', sa.String(length=80), nullable=True),
    sa.Column('evaluation_policy_version', sa.String(length=40), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_model_versions_model_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_id', 'fingerprint', name='model_fingerprint')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_model_id'), ['model_id'], unique=False)

    op.create_table('health_forecasts',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('change_per_hour', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('target_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('lower_bound <= upper_bound', name=op.f('ck_health_forecasts_bounds_ordered')),
    sa.CheckConstraint('predicted_score >= 0 AND predicted_score <= 100', name=op.f('ck_health_forecasts_predicted_range')),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_health_forecasts_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['health_snapshots.id'], name=op.f('fk_health_forecasts_snapshot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_forecasts'))
    )
    with op.batch_alter_table('health_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_forecasts_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_forecasts_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('incidents',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('state', sa.Enum('open', 'diagnosing', 'mitigating', 'verifying', 'resolved', 'failed', name='incident_state', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('closing_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('trough_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['closing_snapshot_id'], ['health_snapshots.id'], name=op.f('fk_incidents_closing_snapshot_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_incidents_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opening_snapshot_id'], ['health_snapshots.id'], name=op.f('fk_incidents_opening_snapshot_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_model_id'), ['model_id'], unique=False)
        batch_op.create_index('ix_incidents_model_opened', ['model_id', 'opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_opened_at'), ['opened_at'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_documents_source_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_documents_superseded_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('source_id', 'external_ref', name='source_external_ref')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_source_id'), ['source_id'], unique=False)

    op.create_table('stability_tests',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('baseline_version_id', sa.String(length=36), nullable=True),
    sa.Column('evaluator_version_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('semantic', 'temporal', name='stability_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('question_redacted', sa.Text(), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('evaluator_confidence', sa.Float(), nullable=True),
    sa.Column('verdict', sa.Enum('stable', 'drifting', 'critical', 'inconclusive', name='stability_verdict', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('inputs_changed', sa.Boolean(), nullable=False),
    sa.Column('changed_inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('evaluator_confidence IS NULL OR (evaluator_confidence >= 0 AND evaluator_confidence <= 1)', name=op.f('ck_stability_tests_evaluator_confidence_range')),
    sa.CheckConstraint('stability_score IS NULL OR (stability_score >= 0 AND stability_score <= 100)', name=op.f('ck_stability_tests_stability_score_range')),
    sa.ForeignKeyConstraint(['baseline_version_id'], ['model_versions.id'], name=op.f('fk_stability_tests_baseline_version_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluator_version_id'], ['evaluator_versions.id'], name=op.f('fk_stability_tests_evaluator_version_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_stability_tests_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_stability_tests_model_version_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_tests'))
    )
    with op.batch_alter_table('stability_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_tests_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_stability_tests_model_id'), ['model_id'], unique=False)
        batch_op.create_index('ix_stability_tests_model_run', ['model_id', 'run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stability_tests_question_hash'), ['question_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_stability_tests_run_at'), ['run_at'], unique=False)

    op.create_table('traces',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('question_redacted', sa.Text(), nullable=True),
    sa.Column('answer_redacted', sa.Text(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('answer_hash', sa.String(length=64), nullable=True),
    sa.Column('redaction_policy_version', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('ok', 'error', 'timeout', 'filtered', name='trace_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('retrieved_document_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('unsupported_claim_count', sa.Integer(), nullable=False),
    sa.Column('groundedness_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('safety_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_traces_latency_non_negative')),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_traces_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_traces_model_version_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_traces_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traces'))
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traces_model_id'), ['model_id'], unique=False)
        batch_op.create_index('ix_traces_model_occurred', ['model_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_prompt_hash'), ['prompt_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alerts',
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('firing', 'acknowledged', 'resolved', name='alert_state', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_alerts_incident_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_alerts_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alerts_rule_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['health_snapshots.id'], name=op.f('fk_alerts_snapshot_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_fired_at'), ['fired_at'], unique=False)
        batch_op.create_index('ix_alerts_model_fired', ['model_id', 'fired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_state'), ['state'], unique=False)

    op.create_table('diagnoses',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('evaluator_version_id', sa.String(length=36), nullable=True),
    sa.Column('probable_cause', sa.String(length=120), nullable=False),
    sa.Column('taxonomy_code', sa.String(length=60), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='diagnosis_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_diagnoses_confidence_range')),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_diagnoses_rank_positive')),
    sa.ForeignKeyConstraint(['evaluator_version_id'], ['evaluator_versions.id'], name=op.f('fk_diagnoses_evaluator_version_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_diagnoses_incident_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_diagnoses_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['health_snapshots.id'], name=op.f('fk_diagnoses_snapshot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses'))
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnoses_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_taxonomy_code'), ['taxonomy_code'], unique=False)

    op.create_table('review_queue_items',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('state', sa.Enum('pending', 'in_review', 'approved', 'rejected', name='review_state', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('assigned_to', sa.String(length=120), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_review_queue_items_incident_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_review_queue_items_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], name=op.f('fk_review_queue_items_trace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue_items'))
    )
    with op.batch_alter_table('review_queue_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_items_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_items_state'), ['state'], unique=False)

    op.create_table('stability_variants',
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.Column('prompt_redacted', sa.Text(), nullable=False),
    sa.Column('answer_redacted', sa.Text(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['stability_tests.id'], name=op.f('fk_stability_variants_test_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], name=op.f('fk_stability_variants_trace_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_variants')),
    sa.UniqueConstraint('test_id', 'variant_index', name='test_variant_index')
    )
    with op.batch_alter_table('stability_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_variants_test_id'), ['test_id'], unique=False)

    op.create_table('diagnosis_evidence',
    sa.Column('diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('reason_code', sa.String(length=60), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('supports_diagnosis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], name=op.f('fk_diagnosis_evidence_diagnosis_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosis_evidence'))
    )
    with op.batch_alter_table('diagnosis_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_evidence_diagnosis_id'), ['diagnosis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_evidence_reason_code'), ['reason_code'], unique=False)

    op.create_table('recovery_plans',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('recommended', 'approved', 'executing', 'recovered', 'failed', name='recovery_state', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('risk', sa.Enum('low', 'medium', 'high', name='risk_level', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('approval_level', sa.Enum('low', 'medium', 'high', name='approval_level', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('simulation', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.String(length=120), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], name=op.f('fk_recovery_plans_diagnosis_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_recovery_plans_incident_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['monitored_models.id'], name=op.f('fk_recovery_plans_model_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_plans')),
    sa.UniqueConstraint('idempotency_key', name='idempotency_key')
    )
    with op.batch_alter_table('recovery_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_plans_diagnosis_id'), ['diagnosis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_plans_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_plans_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_plans_state'), ['state'], unique=False)

    op.create_table('stability_claims',
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('claim_key', sa.String(length=120), nullable=False),
    sa.Column('claim_text_redacted', sa.Text(), nullable=False),
    sa.Column('value_text', sa.String(length=300), nullable=True),
    sa.Column('agrees_with_baseline', sa.Boolean(), nullable=True),
    sa.Column('disagreement_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['stability_tests.id'], name=op.f('fk_stability_claims_test_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['stability_variants.id'], name=op.f('fk_stability_claims_variant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_claims'))
    )
    with op.batch_alter_table('stability_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_claims_claim_key'), ['claim_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_stability_claims_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stability_claims_variant_id'), ['variant_id'], unique=False)

    op.create_table('evidence_traces',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['diagnosis_evidence.id'], name=op.f('fk_evidence_traces_evidence_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], name=op.f('fk_evidence_traces_trace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id', 'trace_id', name=op.f('pk_evidence_traces')),
    comment='Links a piece of evidence to the requests that demonstrate it.'
    )
    op.create_table('recovery_actions',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk', sa.Enum('low', 'medium', 'high', name='risk_level', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('reversible', sa.Boolean(), nullable=False),
    sa.Column('adapter', sa.String(length=80), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('"order" >= 1', name=op.f('ck_recovery_actions_order_positive')),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.id'], name=op.f('fk_recovery_actions_plan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_actions')),
    sa.UniqueConstraint('plan_id', 'order', name='plan_order')
    )
    with op.batch_alter_table('recovery_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_actions_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_actions_plan_id'), ['plan_id'], unique=False)

    op.create_table('verification_runs',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('required_requests', sa.Integer(), nullable=False),
    sa.Column('observed_requests', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('post_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('no_regression_checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('required_requests >= 1', name=op.f('ck_verification_runs_required_requests_positive')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_verification_runs_incident_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.id'], name=op.f('fk_verification_runs_plan_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['health_snapshots.id'], name=op.f('fk_verification_runs_snapshot_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_runs'))
    )
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_runs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_runs_plan_id'), ['plan_id'], unique=False)

    op.create_table('recovery_executions',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('pending', 'running', 'succeeded', 'failed', 'timed_out', 'rolled_back', 'skipped', name='execution_state', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_type', sa.Enum('human', 'system', 'agent', name='actor_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('affected_traffic_pct', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('affected_traffic_pct IS NULL OR (affected_traffic_pct >= 0 AND affected_traffic_pct <= 100)', name=op.f('ck_recovery_executions_traffic_range')),
    sa.CheckConstraint('attempt >= 1', name=op.f('ck_recovery_executions_attempt_positive')),
    sa.ForeignKeyConstraint(['action_id'], ['recovery_actions.id'], name=op.f('fk_recovery_executions_action_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.id'], name=op.f('fk_recovery_executions_plan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_executions')),
    sa.UniqueConstraint('action_id', 'attempt', name='action_attempt')
    )
    with op.batch_alter_table('recovery_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_executions_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_executions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_executions_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_executions_state'))
        batch_op.drop_index(batch_op.f('ix_recovery_executions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_executions_action_id'))

    op.drop_table('recovery_executions')
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_runs_plan_id'))
        batch_op.drop_index(batch_op.f('ix_verification_runs_incident_id'))

    op.drop_table('verification_runs')
    with op.batch_alter_table('recovery_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_actions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_actions_code'))

    op.drop_table('recovery_actions')
    op.drop_table('evidence_traces')
    with op.batch_alter_table('stability_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_claims_variant_id'))
        batch_op.drop_index(batch_op.f('ix_stability_claims_test_id'))
        batch_op.drop_index(batch_op.f('ix_stability_claims_claim_key'))

    op.drop_table('stability_claims')
    with op.batch_alter_table('recovery_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_plans_state'))
        batch_op.drop_index(batch_op.f('ix_recovery_plans_model_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_plans_incident_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_plans_diagnosis_id'))

    op.drop_table('recovery_plans')
    with op.batch_alter_table('diagnosis_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_evidence_reason_code'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_evidence_diagnosis_id'))

    op.drop_table('diagnosis_evidence')
    with op.batch_alter_table('stability_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_variants_test_id'))

    op.drop_table('stability_variants')
    with op.batch_alter_table('review_queue_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_queue_items_state'))
        batch_op.drop_index(batch_op.f('ix_review_queue_items_model_id'))
        batch_op.drop_index(batch_op.f('ix_review_queue_items_created_at'))

    op.drop_table('review_queue_items')
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnoses_taxonomy_code'))
        batch_op.drop_index(batch_op.f('ix_diagnoses_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_diagnoses_model_id'))
        batch_op.drop_index(batch_op.f('ix_diagnoses_incident_id'))

    op.drop_table('diagnoses')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_state'))
        batch_op.drop_index(batch_op.f('ix_alerts_rule_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_model_id'))
        batch_op.drop_index('ix_alerts_model_fired')
        batch_op.drop_index(batch_op.f('ix_alerts_fired_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traces_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_traces_request_id'))
        batch_op.drop_index(batch_op.f('ix_traces_prompt_hash'))
        batch_op.drop_index(batch_op.f('ix_traces_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_traces_model_version_id'))
        batch_op.drop_index('ix_traces_model_occurred')
        batch_op.drop_index(batch_op.f('ix_traces_model_id'))

    op.drop_table('traces')
    with op.batch_alter_table('stability_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_tests_run_at'))
        batch_op.drop_index(batch_op.f('ix_stability_tests_question_hash'))
        batch_op.drop_index('ix_stability_tests_model_run')
        batch_op.drop_index(batch_op.f('ix_stability_tests_model_id'))
        batch_op.drop_index(batch_op.f('ix_stability_tests_kind'))

    op.drop_table('stability_tests')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_source_id'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_opened_at'))
        batch_op.drop_index('ix_incidents_model_opened')
        batch_op.drop_index(batch_op.f('ix_incidents_model_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('health_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_forecasts_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_health_forecasts_model_id'))

    op.drop_table('health_forecasts')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_model_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_fingerprint'))

    op.drop_table('model_versions')
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_model_id'))

    op.drop_table('knowledge_sources')
    with op.batch_alter_table('health_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_snapshots_observed_at'))
        batch_op.drop_index('ix_health_snapshots_model_observed')
        batch_op.drop_index(batch_op.f('ix_health_snapshots_model_id'))

    op.drop_table('health_snapshots')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_model_id'))
        batch_op.drop_index('ix_audit_events_model_created')
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index('ix_audit_events_entity')
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_model_id'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('monitored_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_models_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_monitored_models_name'))

    op.drop_table('monitored_models')
    op.drop_table('tenants')
    op.drop_table('health_policies')
    with op.batch_alter_table('evaluator_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluator_versions_kind'))

    op.drop_table('evaluator_versions')
    with op.batch_alter_table('evaluation_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_feedback_target')

    op.drop_table('evaluation_feedback')
    # ### end Alembic commands ###
