"""Evaluator identity includes kind.

One evaluator build can serve several judgement kinds, and each is a distinct
pinned configuration, so the unique constraint widens from (name, version) to
(name, version, kind).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-06 11:46:54.493182
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluator_versions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('name_version'), type_='unique')
        batch_op.create_unique_constraint('name_version_kind', ['name', 'version', 'kind'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluator_versions', schema=None) as batch_op:
        batch_op.drop_constraint('name_version_kind', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('name_version'), ['name', 'version'])

    # ### end Alembic commands ###
