import { BellRing } from 'lucide-react'
import { useMemo } from 'react'
import { useParams } from 'react-router-dom'
import { EmptyState,ErrorState,LoadingState } from '../components/common/PageState'
import { IncidentCard } from '../components/incidents/IncidentCard'
import { IncidentDetail } from '../components/incidents/IncidentDetail'
import { useDashboard } from '../context/DashboardContext'

export function IncidentsPage(){const{incidentId}=useParams();const{data,loading,error,refresh}=useDashboard();const selected=useMemo(()=>data?.incidents.find(i=>i.id===incidentId)??(incidentId?null:data?.incidents[0]),[data,incidentId]);if(loading)return <div className="page"><LoadingState/></div>;if(error||!data)return <div className="page"><ErrorState message={error??'Incidents could not be loaded.'} onRetry={()=>void refresh()}/></div>;const active=data.incidents.filter(i=>i.state!=='resolved'),resolved=data.incidents.filter(i=>i.state==='resolved');return <div className="page incidents-page"><header className="page-header"><div><p className="eyebrow">Detection & recovery</p><h1>Incidents</h1><p>Diagnose reliability failures, apply recovery, and verify the result.</p></div><div className="header-meta"><BellRing size={14}/> {active.length} active <span className="divider"/> {resolved.length} resolved</div></header>{!data.incidents.length?<div className="panel empty-panel"><EmptyState title="No incidents detected" detail="Models are operating within their reliability thresholds."/></div>:<div className="incidents-layout"><aside className="incident-list"><div className="list-heading"><span>Active incidents</span><strong>{active.length}</strong></div>{active.map(item=><IncidentCard key={item.id} incident={item} selected={selected?.id===item.id}/>)}{resolved.length>0&&<><div className="list-heading resolved-heading"><span>Resolved incidents</span><strong>{resolved.length}</strong></div>{resolved.map(item=><IncidentCard key={item.id} incident={item} selected={selected?.id===item.id}/>)}</>}</aside>{selected?<IncidentDetail incident={selected}/>:<div className="panel empty-panel"><EmptyState title="Select an incident" detail="Choose an incident to inspect its evidence and recovery plan."/></div>}</div>}</div>}
