import { ArrowLeft,Clock3,Database,Radio,ScanSearch } from 'lucide-react'
import { Link,useParams } from 'react-router-dom'
import { HealthChart } from '../components/charts/HealthChart'
import { ErrorState,LoadingState } from '../components/common/PageState'
import { StatusBadge } from '../components/common/StatusBadge'
import { MetricCard } from '../components/models/MetricCard'
import { useDashboard } from '../context/DashboardContext'
import { fullDate,timeAgo } from '../utils/format'

export function ModelDetailPage(){const{modelId}=useParams();const{data,loading,error,refresh}=useDashboard();if(loading)return <div className="page"><LoadingState/></div>;if(error||!data)return <div className="page"><ErrorState message={error??'Model data could not be loaded.'} onRetry={()=>void refresh()}/></div>;const model=data.models.find(m=>m.id===modelId);if(!model)return <div className="page"><ErrorState message="This model is not registered with DriftZero." onRetry={()=>void refresh()}/></div>;const latest=model.trend.at(-1);return <div className="page model-detail-page"><Link to="/models" className="back-link"><ArrowLeft size={14}/>All models</Link><header className="model-detail-header"><div className="model-identity"><div className="model-glyph large">{model.name[0]}</div><div><div><h1>{model.name}</h1><StatusBadge status={model.status}/></div><p>{model.provider} <i/> {model.environment} <i/> {model.lifecycle}</p></div></div><div className={`hero-score ${model.status}`}><span>Health score</span><strong>{model.score===null?'—':Math.round(model.score)}</strong><small>/ 100</small></div></header>
  <section className="metric-grid">{model.metrics.map(metric=><MetricCard key={metric.key} metric={metric}/>)}</section>
  <section className="model-analysis-grid"><article className="panel"><div className="panel-heading"><div><span className="panel-label">Health score over time</span><h2>Reliability trajectory</h2></div><div className="chart-legend"><span><i className="health"/>Health</span><span><i className="ground"/>Groundedness</span><span><i className="stability"/>Stability</span></div></div><HealthChart data={model.trend} height={270} showMetrics/></article><aside className="panel forecast-card"><span className="panel-label">30-minute forecast</span><div className="forecast-score"><strong>{model.forecast?Math.round(model.forecast.score):'—'}</strong><StatusBadge status={model.forecast?.direction==='deteriorating'?'critical':model.forecast?.direction==='recovering'?'warning':'healthy'} label={model.forecast?.direction??'Unavailable'}/></div><p>Projected health from the latest observed trajectory.</p><div className="forecast-details"><div><span>Direction</span><strong>{model.forecast?.direction??'—'}</strong></div><div><span>Coverage</span><strong>{model.coverage!=null?`${Math.round(model.coverage*100)}%`:'—'}</strong></div><div><span>Sample</span><strong>{model.sampleSize??'—'} samples</strong></div></div></aside></section>
  <section className="panel latest-evaluation"><div className="panel-heading"><div><span className="panel-label">Latest evaluation</span><h2>{model.requestId??latest?.time??'No request identifier supplied'}</h2></div><StatusBadge status={model.status==='healthy'?'success':model.status}/></div><div className="evaluation-meta"><div><Clock3/><span>Timestamp</span><strong>{model.lastEvaluation?fullDate(model.lastEvaluation):'Unavailable'}</strong></div><div><Radio/><span>Recency</span><strong>{timeAgo(model.lastEvaluation)}</strong></div><div><Database/><span>Sample size</span><strong>{model.sampleSize??'—'} samples</strong></div><div><ScanSearch/><span>Result</span><strong>{model.status==='healthy'?'Passed':model.status==='critical'?'Failed':'Monitoring'}</strong></div></div></section>
  </div>}
