import { ArrowRight,Clock3,ShieldCheck,TriangleAlert } from 'lucide-react'
import { Link } from 'react-router-dom'
import { HealthChart } from '../components/charts/HealthChart'
import { EmptyState,ErrorState,LoadingState } from '../components/common/PageState'
import { StatusBadge } from '../components/common/StatusBadge'
import { EventTimeline } from '../components/events/EventTimeline'
import { ModelCard } from '../components/models/ModelCard'
import { useDashboard } from '../context/DashboardContext'
import { timeAgo } from '../utils/format'

export function OverviewPage(){const{data,loading,error,refresh}=useDashboard();if(loading)return <div className="page"><LoadingState/></div>;if(error||!data)return <div className="page"><ErrorState message={error??'Dashboard data could not be loaded.'} onRetry={()=>void refresh()}/></div>;const primary=data.models.find(m=>m.status==='critical')??data.models.find(m=>m.name==='ShopAssist')??data.models[0];const active=data.incidents.filter(i=>i.state!=='resolved');const avg=data.models.length?Math.round(data.models.reduce((sum,m)=>sum+(m.score??0),0)/data.models.length):0;return <div className="page overview-page">
  <header className="page-header"><div><p className="eyebrow">Reliability command center</p><h1>AI Reliability Overview</h1><p>Live health, incidents, and recovery across monitored AI systems.</p></div><div className="header-meta"><span className="pulse-dot"/>Monitoring {data.models.length} models <span className="divider"/> Updated just now</div></header>
  <section className="stat-grid"><article className={`stat-card featured ${avg<70?'danger':''}`}><div className="stat-icon"><ShieldCheck size={18}/></div><div><span>Overall health</span><strong>{avg||'—'}</strong><small>{avg>=85?'Within target':'Action required'}</small></div></article><article className="stat-card"><div><span>Active models</span><strong>{data.models.length}</strong><small>{data.models.filter(m=>m.environment.toLowerCase()==='production').length} production</small></div></article><article className="stat-card"><div><span>Active incidents</span><strong>{active.length}</strong><small className={active.length?'negative':'positive'}>{active.length?'Needs attention':'All clear'}</small></div></article><article className="stat-card"><div><span>Evaluations today</span><strong>{data.evaluationsToday.toLocaleString()}</strong><small>Across all models</small></div></article></section>
  {primary&&<section className="dashboard-grid"><ModelCard model={primary} primary/><article className="panel trend-card"><div className="panel-heading"><div><span className="panel-label">Model health trend</span><h2>{primary.status==='healthy'?'Stable performance':primary.status==='warning'?'Recovery in progress':'Degradation detected'}</h2></div><span className="range-select">Last 3 hours</span></div><HealthChart data={primary.trend}/><div className="chart-caption"><span><i className="legend health"/>Health score</span><span className="threshold"><i/>Warning threshold · 70</span>{primary.forecast&&<strong>Forecast: {Math.round(primary.forecast.score)} · {primary.forecast.direction}</strong>}</div></article></section>}
  <section className="lower-grid"><article className="panel"><div className="panel-heading"><div><span className="panel-label">Recent incidents</span><h2>{active.length?'Reliability alerts':'No active incidents'}</h2></div><Link className="text-link" to="/incidents">View all <ArrowRight size={13}/></Link></div>{active.length?<div className="compact-incidents">{active.slice(0,2).map(item=><Link to={`/incidents/${item.id}`} key={item.id}><StatusBadge status={item.severity}/><div><strong>{item.title}</strong><p>{item.modelName} · Health {item.baselineScore} → {item.troughScore}</p></div><span><Clock3 size={12}/>{timeAgo(item.openedAt)}</span></Link>)}</div>:<EmptyState title="Systems are healthy" detail="DriftZero is watching for meaningful degradation."/>}</article><article className="panel"><div className="panel-heading"><div><span className="panel-label">Live event stream</span><h2>Latest activity</h2></div><Link className="text-link" to="/events"><span className="live-label"><i/>Live</span><ArrowRight size={13}/></Link></div>{data.events.length?<EventTimeline events={data.events} limit={3}/>:<EmptyState title="No events yet" detail="Evaluation and recovery activity will appear here."/>}</article></section>
  {primary?.status==='critical'&&<div className="alert-banner"><TriangleAlert size={18}/><div><strong>{primary.name} needs attention</strong><span>Grounding fell below the critical threshold. DriftZero has identified a recovery plan.</span></div><Link to={`/incidents/${active[0]?.id}`}>Review incident <ArrowRight size={14}/></Link></div>}
  </div>}
